#!/bin/sh
set -e

# If the user had installed an old version of starter-kit-camera-slider-demo (before the port to Python 3)
# and ran starter-kit-camera-slider-demo with root permissions, pyc files are created in the installation
# folder. Remove them and all empty folders before installing the new starter-kit-camera-slider-demo version.

if [ -d "/usr/share/starter-kit-camera-slider-demo" ]; then
    find /usr/share/starter-kit-camera-slider-demo -name "*.pyc" -print0 | xargs --null --no-run-if-empty rm
    find /usr/lib/python3/dist-packages/ -type d -empty -print0 | xargs --null --no-run-if-empty rmdir
fi
